### ISSUE TITLE
Extension does not show up in Inkscape 1.2 for Windows

### ISSUE THREAD

**Issue by DWRoelands** [martymcguire/inkscape-openscad-poly#14]
Running Inkscape 1.2.2 on Windows 10.  

Copied the contents of the /src folder to C:\Program Files\Inkscape\share\extensions
Opened a .png file, Shift-Alt-B to "Trace Bitmap".  Preview contains what I want.  Apply.
Select the object, then go to "Path" menu and choose "Object To Path".
Go to "File" and select "Save a Copy".  There is no file type for "OpenSCAD polygons" in the filetype menu.  (see attached screenshot),

Got the same results after copying the contents of the /src folder to C:\Users\[MyUserName]\AppData\Roaming\inkscape\extensions

![InkscapeSaveCopy](https://user-images.githubusercontent.com/829031/219040468-28507876-d54e-4ddb-a937-680b75caeab6.png)

**Comment by martymcguire** [comment]
Thanks @DWRoelands !

I'm not maintaining this extension any longer. The last time I used it myself was a pre-1.0 release of Inkscape!

Leaving this here and open for now in case someone wants to take a crack at it. Otherwise I'll see if I can figure out the last version that this worked with Inkscape and archive it.

**Comment by DWRoelands** [comment]
Ah, I didn't realize the current status of things.  Save your efforts. :)
